// swift-tools-version:5.9
//
// Distribution package for AgentforceService — generated by
// scripts/build-xcframework.sh. Wrapper-pattern: the public library
// product is implemented by AgentforceServiceTarget, which carries the
// binary XCFramework plus its SPM-resolved transitive dependencies.

import PackageDescription

let package = Package(
    name: "AgentforceService",
    platforms: [
        .iOS(.v17)
    ],
    products: [
        // Intentionally NOT `type: .dynamic` (the source Package.swift
        // is). The source declaration enforces dynamic linkage so that
        // AgentforceSDK + AgentforceVoice can both link AgentforceService
        // without duplicate symbols. In the binary path that guarantee
        // already lives in the XCFramework itself — the slices wrapped
        // by AgentforceServiceTarget are dynamic frameworks. The wrapper
        // target is just an `@_exported import` shim with no symbols of
        // its own, so forcing `.dynamic` here would add a second dyld
        // load for an empty re-export.
        .library(
            name: "AgentforceService",
            targets: ["AgentforceServiceTarget"]
        )
    ],
    // Keep in sync with ../../Package.swift — see
    // docs/spm-binary-distribution.md "Dependency-list alignment".
    dependencies: [
        .package(url: "https://github.com/forcedotcom/SalesforceMobileInterfaces-iOS.git", from: "1.0.0"),
        .package(url: "https://github.com/Salesforce-Async-Messaging/SMIClientCore-iOS.swift.git", .upToNextMinor(from: "1.12.0")),
    ],
    targets: [
        .binaryTarget(
            name: "AgentforceService",
            // Adjacent to this Package.swift when distributed locally.
            // For a hosted release, replace with:
            //   url: "https://<host>/AgentforceService-<version>.xcframework.zip",
            //   checksum: "<output of swift package compute-checksum>"
            url: "https://github.com/forcedotcom/AgentforceMobileService-iOS/releases/download/6.17.3/AgentforceMobileService-262-3-spm.xcframework.zip",
            checksum: "4fd5d1ac7eb0c249dd63b44e096f0e9ee3c25afe6bf7091c62245ba1b22e6c6b"
        ),
        .target(
            name: "AgentforceServiceTarget",
            dependencies: [
                "AgentforceService",
                .product(name: "SalesforceNetwork", package: "SalesforceMobileInterfaces-iOS"),
                .product(name: "SalesforceLogging", package: "SalesforceMobileInterfaces-iOS"),
                .product(name: "SMIClientCore", package: "SMIClientCore-iOS.swift"),
            ],
            path: "Sources/AgentforceServiceTarget"
        )
    ]
)
